### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by romulorodrigues**
Adding a new component link

### CODE REVIEW

**Comment by ktquez** [comment]
Hi @romulorodrigues, thanks for your PR.

Could you update and add in order from top to bottom?

**Comment by romulorodrigues** [comment]
Hi! Sorry, I didn't understand the question 😅.

Em dom, 13 de set de 2020 15:55, Alan Ktquez <notifications@github.com>
escreveu:

**Comment by ktquez** [comment]
@romulorodrigues 

It would be adding your repository after the `vue-toggles`

**Review by romulorodrigues — COMMENTED** [review]
changing link position

**Comment by ktquez** [comment]
Thanks @romulorodrigues

**Comment by romulorodrigues** [comment]
I thank you

Em dom, 13 de set de 2020 17:34, Alan Ktquez <notifications@github.com>
escreveu:

**Pull request merged**
